# Generated by Django 5.1.1 on 2024-09-25 01:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coverPhoto', models.ImageField(upload_to='coffee_photos/')),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=100)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_coffee_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('admission_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coffeeShops.coffeeshop')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkwrm_val', models.IntegerField(default=50, help_text='enter a number between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('adv_val', models.IntegerField(default=50, help_text='enter a number between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avgj_val', models.IntegerField(default=50, help_text='enter a number between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acc_val', models.IntegerField(default=50, help_text='enter a number between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coffee_shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoffeeStats', to='coffeeShops.coffeeshop')),
            ],
        ),
    ]
