# Generated by Django 5.1.1 on 2024-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
