# Generated by Django 5.1.1 on 2024-09-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0002_coffeeshop_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='fav',
        ),
    ]
