# Generated by Django 5.1.1 on 2024-09-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0003_remove_coffeeshop_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='coffeeShopSearchDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freqs', models.JSONField(blank=True, default=dict)),
                ('wordTotal', models.IntegerField(default=0)),
                ('coffee_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SearchDoc', to='coffeeShops.coffeeshop')),
            ],
        ),
    ]
