# Generated by Django 5.1.1 on 2024-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0004_coffeeshopsearchdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('coffee_shop_ids', models.JSONField(default=list)),
            ],
        ),
    ]
